/*
 * generated by Xtext 2.9.1
 */
package com.xtext.enseeiht.policyDSL


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PolicyDslStandaloneSetup extends PolicyDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PolicyDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
