/*
 * generated by Xtext 2.9.1
 */
package com.xtext.enseeiht.policyDSL


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PolicyDslRuntimeModule extends AbstractPolicyDslRuntimeModule {
}
