/*
 * generated by Xtext 2.9.1
 */
package com.xtext.enseeiht.policyDSL.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class PolicyDslScopeProvider extends AbstractPolicyDslScopeProvider {

}
